[2024-05-18T15:59:45.464+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v2.seceond_task manual__2024-05-18T15:46:22.886695+00:00 [queued]>
[2024-05-18T15:59:45.473+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v2.seceond_task manual__2024-05-18T15:46:22.886695+00:00 [queued]>
[2024-05-18T15:59:45.474+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-05-18T15:59:45.489+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): seceond_task> on 2024-05-18 15:46:22.886695+00:00
[2024-05-18T15:59:45.496+0000] {standard_task_runner.py:60} INFO - Started process 2954 to run task
[2024-05-18T15:59:45.499+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v2', 'seceond_task', 'manual__2024-05-18T15:46:22.886695+00:00', '--job-id', '371', '--raw', '--subdir', 'DAGS_FOLDER/frist-dag.py', '--cfg-path', '/tmp/tmpqn7x75u6']
[2024-05-18T15:59:45.501+0000] {standard_task_runner.py:88} INFO - Job 371: Subtask seceond_task
[2024-05-18T15:59:45.547+0000] {task_command.py:423} INFO - Running <TaskInstance: our_first_dag_v2.seceond_task manual__2024-05-18T15:46:22.886695+00:00 [running]> on host 7b23a6949395
[2024-05-18T15:59:45.634+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='our_first_dag_v2' AIRFLOW_CTX_TASK_ID='seceond_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-18T15:46:22.886695+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-18T15:46:22.886695+00:00'
[2024-05-18T15:59:45.639+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-18T15:59:45.640+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'ls /opt/***']
[2024-05-18T15:59:45.657+0000] {subprocess.py:86} INFO - Output:
[2024-05-18T15:59:45.675+0000] {subprocess.py:93} INFO - ***-worker.pid
[2024-05-18T15:59:45.676+0000] {subprocess.py:93} INFO - ***.cfg
[2024-05-18T15:59:45.676+0000] {subprocess.py:93} INFO - config
[2024-05-18T15:59:45.677+0000] {subprocess.py:93} INFO - dags
[2024-05-18T15:59:45.677+0000] {subprocess.py:93} INFO - logs
[2024-05-18T15:59:45.678+0000] {subprocess.py:93} INFO - output.csv
[2024-05-18T15:59:45.678+0000] {subprocess.py:93} INFO - plugins
[2024-05-18T15:59:45.678+0000] {subprocess.py:93} INFO - webserver_config.py
[2024-05-18T15:59:45.679+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-18T15:59:45.707+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v2, task_id=seceond_task, execution_date=20240518T154622, start_date=20240518T155945, end_date=20240518T155945
[2024-05-18T15:59:45.752+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-18T15:59:45.771+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
