[2024-05-19T18:19:38.756+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v2.seceond_task manual__2024-05-19T18:19:33.780693+00:00 [queued]>
[2024-05-19T18:19:38.770+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v2.seceond_task manual__2024-05-19T18:19:33.780693+00:00 [queued]>
[2024-05-19T18:19:38.771+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-05-19T18:19:38.788+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): seceond_task> on 2024-05-19 18:19:33.780693+00:00
[2024-05-19T18:19:38.797+0000] {standard_task_runner.py:60} INFO - Started process 93 to run task
[2024-05-19T18:19:38.800+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v2', 'seceond_task', 'manual__2024-05-19T18:19:33.780693+00:00', '--job-id', '384', '--raw', '--subdir', 'DAGS_FOLDER/frist-dag.py', '--cfg-path', '/tmp/tmp4idne1po']
[2024-05-19T18:19:38.801+0000] {standard_task_runner.py:88} INFO - Job 384: Subtask seceond_task
[2024-05-19T18:19:38.848+0000] {task_command.py:423} INFO - Running <TaskInstance: our_first_dag_v2.seceond_task manual__2024-05-19T18:19:33.780693+00:00 [running]> on host 7b23a6949395
[2024-05-19T18:19:38.930+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='our_first_dag_v2' AIRFLOW_CTX_TASK_ID='seceond_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-19T18:19:33.780693+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-19T18:19:33.780693+00:00'
[2024-05-19T18:19:38.932+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-19T18:19:38.933+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'wc -l /opt/***/output.csv']
[2024-05-19T18:19:38.948+0000] {subprocess.py:86} INFO - Output:
[2024-05-19T18:19:39.091+0000] {subprocess.py:93} INFO - 240019 /opt/***/output.csv
[2024-05-19T18:19:39.092+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-19T18:19:39.114+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v2, task_id=seceond_task, execution_date=20240519T181933, start_date=20240519T181938, end_date=20240519T181939
[2024-05-19T18:19:39.133+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-19T18:19:39.148+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
