[2024-05-18T15:36:28.531+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v2.seceond_task manual__2024-05-18T15:36:24.055079+00:00 [queued]>
[2024-05-18T15:36:28.541+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v2.seceond_task manual__2024-05-18T15:36:24.055079+00:00 [queued]>
[2024-05-18T15:36:28.542+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-05-18T15:36:28.560+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): seceond_task> on 2024-05-18 15:36:24.055079+00:00
[2024-05-18T15:36:28.568+0000] {standard_task_runner.py:60} INFO - Started process 2606 to run task
[2024-05-18T15:36:28.571+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v2', 'seceond_task', 'manual__2024-05-18T15:36:24.055079+00:00', '--job-id', '369', '--raw', '--subdir', 'DAGS_FOLDER/frist-dag.py', '--cfg-path', '/tmp/tmp39on1gin']
[2024-05-18T15:36:28.573+0000] {standard_task_runner.py:88} INFO - Job 369: Subtask seceond_task
[2024-05-18T15:36:28.631+0000] {task_command.py:423} INFO - Running <TaskInstance: our_first_dag_v2.seceond_task manual__2024-05-18T15:36:24.055079+00:00 [running]> on host 7b23a6949395
[2024-05-18T15:36:28.723+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='our_first_dag_v2' AIRFLOW_CTX_TASK_ID='seceond_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-18T15:36:24.055079+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-18T15:36:24.055079+00:00'
[2024-05-18T15:36:28.725+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-18T15:36:28.727+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'ls /opt/***']
[2024-05-18T15:36:28.742+0000] {subprocess.py:86} INFO - Output:
[2024-05-18T15:36:28.754+0000] {subprocess.py:93} INFO - ***-worker.pid
[2024-05-18T15:36:28.755+0000] {subprocess.py:93} INFO - ***.cfg
[2024-05-18T15:36:28.755+0000] {subprocess.py:93} INFO - config
[2024-05-18T15:36:28.756+0000] {subprocess.py:93} INFO - dags
[2024-05-18T15:36:28.756+0000] {subprocess.py:93} INFO - logs
[2024-05-18T15:36:28.757+0000] {subprocess.py:93} INFO - output.csv
[2024-05-18T15:36:28.757+0000] {subprocess.py:93} INFO - plugins
[2024-05-18T15:36:28.758+0000] {subprocess.py:93} INFO - webserver_config.py
[2024-05-18T15:36:28.758+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-18T15:36:28.787+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v2, task_id=seceond_task, execution_date=20240518T153624, start_date=20240518T153628, end_date=20240518T153628
[2024-05-18T15:36:28.825+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-18T15:36:28.845+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
