[2024-05-18T14:28:55.290+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v2.seceond_task manual__2024-05-18T14:28:51.926863+00:00 [queued]>
[2024-05-18T14:28:55.298+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v2.seceond_task manual__2024-05-18T14:28:51.926863+00:00 [queued]>
[2024-05-18T14:28:55.299+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-05-18T14:28:55.311+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): seceond_task> on 2024-05-18 14:28:51.926863+00:00
[2024-05-18T14:28:55.319+0000] {standard_task_runner.py:60} INFO - Started process 1362 to run task
[2024-05-18T14:28:55.321+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v2', 'seceond_task', 'manual__2024-05-18T14:28:51.926863+00:00', '--job-id', '317', '--raw', '--subdir', 'DAGS_FOLDER/frist-dag.py', '--cfg-path', '/tmp/tmpujt4twm1']
[2024-05-18T14:28:55.323+0000] {standard_task_runner.py:88} INFO - Job 317: Subtask seceond_task
[2024-05-18T14:28:55.363+0000] {task_command.py:423} INFO - Running <TaskInstance: our_first_dag_v2.seceond_task manual__2024-05-18T14:28:51.926863+00:00 [running]> on host 7b23a6949395
[2024-05-18T14:28:55.433+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='our_first_dag_v2' AIRFLOW_CTX_TASK_ID='seceond_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-18T14:28:51.926863+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-18T14:28:51.926863+00:00'
[2024-05-18T14:28:55.435+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-18T14:28:55.436+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'pwd']
[2024-05-18T14:28:55.450+0000] {subprocess.py:86} INFO - Output:
[2024-05-18T14:28:55.451+0000] {subprocess.py:93} INFO - /tmp/***tmpdgnhq2oh
[2024-05-18T14:28:55.452+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-18T14:28:55.474+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v2, task_id=seceond_task, execution_date=20240518T142851, start_date=20240518T142855, end_date=20240518T142855
[2024-05-18T14:28:55.494+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-18T14:28:55.511+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
